const products = [
    {
        _id: '1',
        name: 'All New Mahindra Thar 2022',
        image: '/images/thar.png',
        description: 'A modern take on an iconic design, the All-New Thar, with its wide stance and iconic lines, stands out wherever it goes. ',
        brand: 'Mahindra',
        category:'Car',
        price: 1600000,
        countInStock:3,
        rating:4.3,
        numReviews:7,
    },
    {
        _id: '2',
        name: 'Audi 2022',
        image: '/images/audi.png',
        description: 'A modern take on an iconic design, the All-New Thar, with its wide stance and iconic lines, stands out wherever it goes. ',
        brand: 'Audi',
        category:'Car',
        price: 11800000,
        countInStock:2,
        rating:2.3,
        numReviews:9,
    },
    {
        _id: '3',
        name: 'BMW 2022',
        image: '/images/bmw.png',
        description: 'A modern take on an iconic design, the All-New Thar, with its wide stance and iconic lines, stands out wherever it goes. ',
        brand: 'Bmw',
        category:'Car',
        price: 21400000,
        countInStock:2,
        rating:4,
        numReviews:10,
    },
    {
        _id: '4',
        name: 'All New Bugatti 2022',
        image: '/images/bugatti.png',
        description: 'A modern take on an iconic design, the All-New Thar, with its wide stance and iconic lines, stands out wherever it goes. ',
        brand: 'Bugatti',
        category:'Car',
        price: 51600000,
        countInStock:1,
        rating:5,
        numReviews:41,
    },
    {
        _id: '5',
        name: 'Range Rover 2022',
        image: '/images/rr.png',
        description: 'A modern take on an iconic design, the All-New Thar, with its wide stance and iconic lines, stands out wherever it goes. ',
        brand: 'Range Rover',
        category:'Car',
        price: 21600000,
        countInStock:3,
        rating:4.4,
        numReviews:8,
    },
    {
        _id: '6',
        name: 'All New Ferrari',
        image: '/images/far.png',
        description: 'A modern take on an iconic design, the All-New Thar, with its wide stance and iconic lines, stands out wherever it goes. ',
        brand: 'Ferrari',
        category:'Car',
        price: 21600000,
        countInStock:3,
        rating:4.4,
        numReviews:7,
    }
]

export default products;